### ISSUE TITLE
joestakey - `FlashAction` can be used to re-take a loan against the same collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-astaria-judging#109]
joestakey

high

# `FlashAction` can be used to re-take a loan against the same collateral

## Summary
Users can use `FlashAction` to take a loan using that same collateral NFT.

## Vulnerability Detail
`FlashAction` allows the user to unlock their underlying collateral and perform any action with the NFT as long as it is returned within the same block.

The issue is that they can use that NFT to take a new loan:

If the attacker contract implements`receiver.onFlashAction` so that it calls `AstariaRouter.commitToLiens`, this will result in srtarting a new loan, and transferring the NFT to the `COLLATERAL_TOKEN` contract.
At the end of the call, the [check](https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L193-L196) that the NFT is returned will hence pass.

## Impact
This new loan uses the same collateral as the previous one, meaning the user effectively took this new loan for free

## Code Snippet
https://github.com/sherlock-audit/2022-10-astaria/blob/main/src/CollateralToken.sol#L193-L196

## Tool used

Manual Review

## Recommendation
Consider checking the underlying balance of the vault in `flashAction()`, ensuring it has not changed at the end of the call.

**Comment by IAmTurnipBoy** [comment]
Escalate for 1 USDC

Impossible due to (this line)[https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/AstariaRouter.sol#L265]. Because the collateral token already exists it wouldn't make a new collateral token and this transfer would fail, reverting the whole transaction.

As additional context, the attacker is unable to just send the collateral token to the contract to receive it again because _executeCommitment requires the attacker to be owner of the collateral token.

Relevant lines:
https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/AstariaRouter.sol#L559

Edit: I have been made aware that the reason why the scenario in this report doesn't work on the current contracts is because AstariaRouter::commitToLiens itself is a function that doesn't work, see #204. Puts this submission in an interesting area from a judging perspective.

**Comment by sherlock-admin** [comment]
> Escalate for 1 USDC
> 
> Impossible due to (this line)[https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/AstariaRouter.sol#L265]. Because the collateral token already exists it wouldn't make a new collateral token and this transfer would fail, reverting the whole transaction.
> 
> As additional context, the attacker is unable to just send the collateral token to the contract to receive it again because _executeCommitment requires the attacker to be owner of the collateral token.
> 
> Relevant lines:
> https://github.com/sherlock-audit/2022-10-astaria/blob/7d12a5516b7c74099e1ce6fb4ec87c102aec2786/src/AstariaRouter.sol#L559
> 
> Edit: I have been made aware that the reason why the scenario in this report doesn't work on the current contracts is because AstariaRouter::commitToLiens itself is a function that doesn't work, see #204. Puts this submission in an interesting area from a judging perspective.

You've created a valid escalation for 1 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted because of clear explanation from @IAmTurnipBoy

**Comment by sherlock-admin** [comment]
> Escalation accepted because of clear explanation from @IAmTurnipBoy 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
